// <auto-generated />
using System;
using FormationContinue.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace FormationContinue.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260120024450_AddQcmModels")]
    partial class AddQcmModels
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FormationContinue.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.HasKey("Id");

                    b.HasIndex("Libelle")
                        .IsUnique();

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("FormationContinue.Models.Choix", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EstCorrect")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)");

                    b.Property<int>("QuestionId")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.ToTable("Choix");
                });

            modelBuilder.Entity("FormationContinue.Models.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<byte[]>("ContenuPdf")
                        .HasColumnType("BLOB");

                    b.Property<DateTime?>("DatePublication")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Etat")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)");

                    b.Property<string>("MotsCles")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)");

                    b.Property<string>("NomFichierPdf")
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)");

                    b.Property<string>("Titre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("FormationContinue.Models.CourseProfessor", b =>
                {
                    b.Property<int>("CourseId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("ProfessorId")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("CourseId", "ProfessorId");

                    b.HasIndex("ProfessorId");

                    b.ToTable("CourseProfessors");
                });

            modelBuilder.Entity("FormationContinue.Models.Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Enonce")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<double>("Points")
                        .HasColumnType("BINARY_DOUBLE");

                    b.HasKey("Id");

                    b.ToTable("Questions");
                });

            modelBuilder.Entity("FormationContinue.Models.QuestionCourse", b =>
                {
                    b.Property<int>("CourseId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("QuestionId")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("CourseId", "QuestionId");

                    b.HasIndex("QuestionId");

                    b.ToTable("CourseQuestions");
                });

            modelBuilder.Entity("FormationContinue.Models.ReponseTentative", b =>
                {
                    b.Property<int>("TentativeQcmId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("ChoixId")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("TentativeQcmId", "ChoixId");

                    b.HasIndex("ChoixId");

                    b.ToTable("ReponseTentatives");
                });

            modelBuilder.Entity("FormationContinue.Models.ResultatQuestion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EstCorrect")
                        .HasColumnType("NUMBER(10)");

                    b.Property<double>("PointsObtenus")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<int>("QuestionId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("TentativeQcmId")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.HasIndex("TentativeQcmId", "QuestionId")
                        .IsUnique();

                    b.ToTable("ResultatQuestions");
                });

            modelBuilder.Entity("FormationContinue.Models.TentativeQcm", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CourseId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<DateTime>("DateTentative")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<double>("NoteSur20")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<string>("StatutTentative")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)");

                    b.Property<int>("UserId")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("UserId");

                    b.ToTable("TentativesQcm");
                });

            modelBuilder.Entity("FormationContinue.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("NVARCHAR2(120)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("NVARCHAR2(64)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("NVARCHAR2(400)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("FormationContinue.Models.Choix", b =>
                {
                    b.HasOne("FormationContinue.Models.Question", "Question")
                        .WithMany("Choix")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("FormationContinue.Models.Course", b =>
                {
                    b.HasOne("FormationContinue.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("FormationContinue.Models.CourseProfessor", b =>
                {
                    b.HasOne("FormationContinue.Models.Course", "Course")
                        .WithMany("CourseProfessors")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FormationContinue.Models.User", "Professor")
                        .WithMany()
                        .HasForeignKey("ProfessorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Professor");
                });

            modelBuilder.Entity("FormationContinue.Models.QuestionCourse", b =>
                {
                    b.HasOne("FormationContinue.Models.Course", "Course")
                        .WithMany("CourseQuestions")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FormationContinue.Models.Question", "Question")
                        .WithMany("QuestionCourses")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Question");
                });

            modelBuilder.Entity("FormationContinue.Models.ReponseTentative", b =>
                {
                    b.HasOne("FormationContinue.Models.Choix", "Choix")
                        .WithMany("ReponseTentatives")
                        .HasForeignKey("ChoixId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FormationContinue.Models.TentativeQcm", "TentativeQcm")
                        .WithMany("ReponseTentatives")
                        .HasForeignKey("TentativeQcmId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Choix");

                    b.Navigation("TentativeQcm");
                });

            modelBuilder.Entity("FormationContinue.Models.ResultatQuestion", b =>
                {
                    b.HasOne("FormationContinue.Models.Question", "Question")
                        .WithMany("ResultatQuestions")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FormationContinue.Models.TentativeQcm", "TentativeQcm")
                        .WithMany("ResultatQuestions")
                        .HasForeignKey("TentativeQcmId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Question");

                    b.Navigation("TentativeQcm");
                });

            modelBuilder.Entity("FormationContinue.Models.TentativeQcm", b =>
                {
                    b.HasOne("FormationContinue.Models.Course", "Course")
                        .WithMany("TentativesQcm")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FormationContinue.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FormationContinue.Models.Choix", b =>
                {
                    b.Navigation("ReponseTentatives");
                });

            modelBuilder.Entity("FormationContinue.Models.Course", b =>
                {
                    b.Navigation("CourseProfessors");

                    b.Navigation("CourseQuestions");

                    b.Navigation("TentativesQcm");
                });

            modelBuilder.Entity("FormationContinue.Models.Question", b =>
                {
                    b.Navigation("Choix");

                    b.Navigation("QuestionCourses");

                    b.Navigation("ResultatQuestions");
                });

            modelBuilder.Entity("FormationContinue.Models.TentativeQcm", b =>
                {
                    b.Navigation("ReponseTentatives");

                    b.Navigation("ResultatQuestions");
                });
#pragma warning restore 612, 618
        }
    }
}
